import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import styles from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.page}>
          {children}
          <footer className={styles.footer}>
            <a href="music" rel="noopener noreferrer">
              <Image
                aria-hidden
                src="/file.svg"
                alt="File icon"
                width={16}
                height={16}
              />
              Music
            </a>
            <a href="video" rel="noopener noreferrer">
              <Image
                aria-hidden
                src="/window.svg"
                alt="Window icon"
                width={16}
                height={16}
              />
              Video
            </a>
            <a href="timer" rel="noopener noreferrer">
              <Image
                aria-hidden
                src="/globe.svg"
                alt="Globe icon"
                width={16}
                height={16}
              />
              Timer
            </a>
            <a href="battery" rel="noopener noreferrer">
              <Image
                aria-hidden
                src="/file.svg"
                alt="File icon"
                width={16}
                height={16}
              />
              Battery
            </a>
            <a href="device" rel="noopener noreferrer">
              <Image
                aria-hidden
                src="/window.svg"
                alt="Window icon"
                width={16}
                height={16}
              />
              Device
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
